apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xg3j56iwh-java-springboot
  janus-idp.io/tekton: xg3j56iwh-java-springboot
  backstage.io/kubernetes-id: xg3j56iwh-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xg3j56iwh-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
